#ArtMap Brushes Addon config

#The URL for the resource pack to send players when they mount an easel
#Default resource pack created by NullBlox (https://www.spigotmc.org/members/nullblox.3822/)
resourcePackURL: https://www.dropbox.com/sh/gmb82pjw6vjkks1/AACEpQAOFtRzqd92Ps3QcgH5a?dl=1